name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Shanghai
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          plugin_poopmap_token: 90b1815349b1b53954109f6c264762fe
          plugin_poopmap: yes
          filename: metrics.plugin.poopmap.svg
          config_timezone: Asia/Shanghai
